name: linter-check
on: [push]
jobs:
  linter:
     runs-on: ubuntu-latest
     steps:
     - uses: actions/checkout@v2
     - name: Install dependencies
       run: pip install poetry
       run: make install
     - run: make lint
